- pkg:maven/com.jdcloud.sdk/kubernetes@0.3.0
- pkg:maven/com.jdcloud.sdk/kubernetes@0.3.0?classifier=sources
- pkg:maven/com.jdcloud.sdk/kubernetes@0.4.0
- pkg:maven/com.jdcloud.sdk/kubernetes@0.4.0?classifier=sources
- pkg:maven/com.jdcloud.sdk/kubernetes@0.5.1
- pkg:maven/com.jdcloud.sdk/kubernetes@0.5.1?classifier=sources
