- pkg:maven/io.github.ddk-prog/cxf-prometheus-metrics@1.0.0
- pkg:maven/io.github.ddk-prog/cxf-prometheus-metrics@1.0.0?classifier=sources
- pkg:maven/io.github.ddk-prog/cxf-prometheus-metrics@1.1.1
- pkg:maven/io.github.ddk-prog/cxf-prometheus-metrics@1.1.1?classifier=sources
