- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.1-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.1-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.0.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.0.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.1.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.1.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.2.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@3.2.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.0.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.0.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.1.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.1.0-RELEASE?classifier=sources
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.2.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@4.2.0-RELEASE?classifier=sources
