- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.0-RELEASE
- pkg:maven/com.ringcentral.platform.metrics/metrics-facade-dropwizard-to-prometheus@2.1.0-RELEASE?classifier=sources
