- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28.1
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28.1?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28?classifier=sources
