- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28.1
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28.1?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.28?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.29
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.29.1
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.29.1?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.29?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@1.30?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@2.0?classifier=sources
- pkg:maven/us.abstracta.jmeter/jmeter-java-dsl-prometheus@2.1?classifier=sources
