- pkg:maven/io.github.pig-mesh.ai/spring-ai-spring-boot-docker-compose@1.1.3?classifier=sources
- pkg:maven/io.github.pig-mesh.ai/spring-ai-spring-boot-docker-compose@1.1.4?classifier=sources
- pkg:maven/io.github.pig-mesh.ai/spring-ai-spring-boot-docker-compose@1.1.5?classifier=sources
- pkg:maven/io.github.pig-mesh.ai/spring-ai-spring-boot-docker-compose@1.1.6?classifier=sources
